--
-- This file is part of Port@l
-- Port@l 3.0 - Portal Engine and Management System
-- Copyright (C) 2010  Isotrol, SA.  http://www.isotrol.com
--
-- Port@l is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- Port@l is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with Port@l.  If not, see <http://www.gnu.org/licenses/>.
--

-- Table: ENVIRONMENT
CREATE INDEX IDX_ENVIRONMENT_FK1 ON ENVIRONMENT(EDTN_ID);

-- Table: EDITION
CREATE INDEX IDX_EDITION_FK1 ON EDITION(ENVT_ID);

-- Table: CONTENT_TYPE
CREATE INDEX IDX_CONTENT_TYPE_FK1 ON CONTENT_TYPE(ENVT_ID);
CREATE INDEX IDX_CONTENT_TYPE_FK2 ON CONTENT_TYPE(COTP_DFN_ID);

-- Table: CONTENT_TYPE_DFN
CREATE INDEX IDX_CONTENT_TYPE_DFN_FK1 ON CONTENT_TYPE_DFN(COTP_ID);

-- Table: CONTENT_TYPE_L7D
CREATE INDEX IDX_CONTENT_TYPE_L7D_FK1 ON CONTENT_TYPE_L7D(COTP_ID);

-- Table: CONTENT_TYPE_EDITION
CREATE INDEX IDX_CONTENT_TYPE_EDITION_FK1 ON CONTENT_TYPE_EDITION(EDTN_ID);
CREATE INDEX IDX_CONTENT_TYPE_EDITION_FK2 ON CONTENT_TYPE_EDITION(COTP_DFN_ID);

-- Table: CATEGORY
CREATE INDEX IDX_CATEGORY_FK1 ON CATEGORY(ENVT_ID);
CREATE INDEX IDX_CATEGORY_FK2 ON CATEGORY(CTGY_DFN_ID);

-- Table: CATEGORY_DFN
CREATE INDEX IDX_CATEGORY_DFN_FK1 ON CATEGORY_DFN(CTGY_ID);
CREATE INDEX IDX_CATEGORY_DFN_FK2 ON CATEGORY_DFN(CTGY_PARENT_ID);

-- Table: CATEGORY_L7D
CREATE INDEX IDX_CATEGORY_L7D_FK1 ON CATEGORY_L7D(COTP_ID);

-- Table: CATEGORY_EDITION
CREATE INDEX IDX_CATEGORY_EDITION_FK1 ON CATEGORY_EDITION(EDTN_ID);
CREATE INDEX IDX_CATEGORY_EDITION_FK2 ON CATEGORY_EDITION(CTGY_DFN_ID);

-- Table: SOURCE_MAPPING
CREATE INDEX IDX_SOURCE_MAPPING_FK1 ON SOURCE_MAPPING(ENVT_ID);

-- Table: ROUTING_DOMAIN
CREATE INDEX IDX_ROUTING_DOMAIN_FK1 ON ROUTING_DOMAIN(ENVT_ID);

-- Table: SET_MAPPING
CREATE INDEX IDX_SET_MAPPING_FK1 ON SET_MAPPING(SRCM_ID);

-- Table: CONTENT_TYPE_MAPPING
CREATE INDEX IDX_CONTENT_TYPE_MAPPING_FK1 ON CONTENT_TYPE_MAPPING(SRCM_ID);
CREATE INDEX IDX_CONTENT_TYPE_MAPPING_FK2 ON CONTENT_TYPE_MAPPING(COTP_ID);

-- Table: CATEGORY_MAPPING
CREATE INDEX IDX_CATEGORY_MAPPING_FK1 ON CATEGORY_MAPPING(SRCM_ID);
CREATE INDEX IDX_CATEGORY_MAPPING_FK2 ON CATEGORY_MAPPING(CTGY_ID);

-- Table: CONNECTOR
CREATE INDEX IDX_CONNECTOR_FK1 ON CONNECTOR(ENVT_ID);
CREATE INDEX IDX_CONNECTOR_FK2 ON CONNECTOR(CNNT_DFN_ID);

-- Table: CONNECTOR_DFN
CREATE INDEX IDX_CONNECTOR_DFN_FK1 ON CONNECTOR_DFN(CNNT_ID);
CREATE INDEX IDX_CONNECTOR_DFN_FK2 ON CONNECTOR_DFN(CNFG_ID);

-- Table: CONNECTOR_DEPS
CREATE INDEX IDX_CONNECTOR_DEPS_FK1 ON CONNECTOR_DEPS(CNNT_DFN_ID);
CREATE INDEX IDX_CONNECTOR_DEPS_FK2 ON CONNECTOR_DEPS(CNNT_ID);

-- Table: CONNECTOR_EDITION
CREATE INDEX IDX_CONNECTOR_EDITION_FK1 ON CONNECTOR_EDITION(EDTN_ID);
CREATE INDEX IDX_CONNECTOR_EDITION_FK2 ON CONNECTOR_EDITION(CNNT_DFN_ID);

-- Table: CONFIGURATION_VALUE
CREATE INDEX IDX_CONFIGURATION_VALUE_FK1 ON CONFIGURATION_VALUE(CNFG_ID);
CREATE INDEX IDX_CONFIGURATION_VALUE_FK2 ON CONFIGURATION_VALUE(CV_FLDT_ID);
CREATE INDEX IDX_CONFIGURATION_VALUE_FK3 ON CONFIGURATION_VALUE(CV_COTP_ID);
CREATE INDEX IDX_CONFIGURATION_VALUE_FK4 ON CONFIGURATION_VALUE(CV_CTGY_ID);

-- Table: DEVICE
CREATE INDEX IDX_DEVICE_FK1 ON DEVICE(PARENT_DVCE_ID);

-- Table: DEVICE_PROPERTY
CREATE INDEX IDX_DEVICE_PROPERTY_FK1 ON DEVICE_PROPERTY(DVCE_ID);

-- Table: PORTAL
CREATE INDEX IDX_PORTAL_FK1 ON PORTAL(ENVT_ID);
CREATE INDEX IDX_PORTAL_FK2 ON PORTAL(PRTL_DFN_ID);
CREATE INDEX IDX_PORTAL_FK3 ON PORTAL(DVCE_ID);

-- Table: PORTAL_DFN
CREATE INDEX IDX_PORTAL_DFN_FK1 ON PORTAL_DFN(PRTL_ID);
CREATE INDEX IDX_PORTAL_DFN_FK2 ON PORTAL_DFN(RTDM_ID);
CREATE INDEX IDX_PORTAL_DFN_FK3 ON PORTAL_DFN(PARENT_PRTL_ID);
CREATE INDEX IDX_PORTAL_DFN_FK4 ON PORTAL_DFN(ROUTER_CNNT_ID);
CREATE INDEX IDX_PORTAL_DFN_FK5 ON PORTAL_DFN(LOCALE_CNNT_ID);
CREATE INDEX IDX_PORTAL_DFN_FK6 ON PORTAL_DFN(DEVICE_CNNT_ID);
CREATE INDEX IDX_PORTAL_DFN_FK7 ON PORTAL_DFN(DEVCAP_CNNT_ID);
CREATE INDEX IDX_PORTAL_DFN_FK8 ON PORTAL_DFN(NR_CNNT_ID);

-- Table: PORTAL_EDITION
CREATE INDEX IDX_PORTAL_EDITION_FK1 ON PORTAL_EDITION(EDTN_ID);
CREATE INDEX IDX_PORTAL_EDITION_FK2 ON PORTAL_EDITION(PRTL_DFN_ID);

-- Table: PORTAL_BASE
CREATE INDEX IDX_PORTAL_BASE_FK1 ON PORTAL_BASE(PRTL_ID);

-- Table: PORTAL_PROPERTY
CREATE INDEX IDX_PORTAL_PROPERTY_FK1 ON PORTAL_PROPERTY(PRTL_ID);

-- Table: PORTAL_COMPONENT_DFN
CREATE INDEX IDX_PORTAL_COMPONENT_DFN_FK1 ON PORTAL_COMPONENT_DFN(PRTL_ID);

-- Table: PORTAL_PAGE_DFN
CREATE INDEX IDX_PORTAL_PAGE_DFN_FK1 ON PORTAL_PAGE_DFN(PRTL_ID);

-- Table: PORTAL_LOCALE
CREATE INDEX IDX_PORTAL_LOCALE_FK1 ON PORTAL_LOCALE(PRTL_ID);

-- Table: PORTAL_AVAILABLE_LOCALE
CREATE INDEX IDX_PORTAL_AVAIL_LOC_FK1 ON PORTAL_AVAILABLE_LOCALE(PRTL_ID);

-- Table: PORTAL_COMPONENT_OVERRIDE
CREATE INDEX IDX_PORTAL_COMP_OVER_FK1 ON PORTAL_COMPONENT_OVERRIDE(OCMP_CNFG_ID);
CREATE INDEX IDX_PORTAL_COMP_OVER_FK2 ON PORTAL_COMPONENT_OVERRIDE(OCMP_DPNS_ID);

-- Table: PORTAL_SET_FILTER
CREATE INDEX IDX_PORTAL_SET_FILTER_FK1 ON PORTAL_SET_FILTER(PRTL_ID);

-- Table: PORTAL_DEVICE

-- Table: PMS_DEPENDENCY_ITEM
CREATE INDEX IDX_PMS_DEPENDENCY_ITEM_FK1 ON PMS_DEPENDENCY_ITEM(DPNS_ID);
CREATE INDEX IDX_PMS_DEPENDENCY_ITEM_FK2 ON PMS_DEPENDENCY_ITEM(CNNT_ID);

-- Table: COMPONENT
CREATE INDEX IDX_COMPONENT_FK1 ON COMPONENT(PRTL_ID);

-- Table: COMPONENT_DFN
CREATE INDEX IDX_COMPONENT_DFN_FK1 ON COMPONENT_DFN(CMPT_ID);
CREATE INDEX IDX_COMPONENT_DFN_FK2 ON COMPONENT_DFN(CNFG_ID);

-- Table: PAGE
CREATE INDEX IDX_PAGE_FK1 ON PAGE(PRTL_ID);
CREATE INDEX IDX_PAGE_FK2 ON PAGE(DVCE_ID);

-- Table: PAGE_DFN
CREATE INDEX IDX_PAGE_DFN_FK1 ON PAGE_DFN(PAGE_ID);
CREATE INDEX IDX_PAGE_DFN_FK2 ON PAGE_DFN(CTGY_ID);
CREATE INDEX IDX_PAGE_DFN_FK3 ON PAGE_DFN(COTP_ID);
CREATE INDEX IDX_PAGE_DFN_FK4 ON PAGE_DFN(TMPL_ID);

-- Table: PAGE_CIP
CREATE INDEX IDX_PAGE_CIP_FK1 ON PAGE_CIP(PAGE_ID);
CREATE INDEX IDX_PAGE_CIP_FK2 ON PAGE_CIP(CMPT_ID);
CREATE INDEX IDX_PAGE_CIP_FK3 ON PAGE_CIP(CNFG_ID);

-- Table: PAGE_LAYOUT
CREATE INDEX IDX_PAGE_LAYOUT_FK1 ON PAGE_LAYOUT(PAGE_ID);
