--
-- This file is part of Port@l
-- Port@l 3.0 - Portal Engine and Management System
-- Copyright (C) 2010  Isotrol, SA.  http://www.isotrol.com
--
-- Port@l is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- Port@l is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with Port@l.  If not, see <http://www.gnu.org/licenses/>.
--

UPDATE PORTAL SET PRTL_DFN_ID=NULL;
UPDATE CONNECTOR SET CNNT_DFN_ID=NULL;
UPDATE CATEGORY SET CTGY_DFN_ID=NULL;
UPDATE CONTENT_TYPE SET COTP_DFN_ID=NULL;
UPDATE ENVIRONMENT SET EDTN_ID=NULL;
DELETE FROM CONFIGURATION_VALUE;
DELETE FROM FILE_DATA;
DELETE FROM PAGE_LAYOUT;
DELETE FROM PAGE_CIP;
DELETE FROM PORTAL_PAGE_DFN;
DELETE FROM PAGE_DFN;
DELETE FROM PAGE;
DELETE FROM PORTAL_COMPONENT_DFN;
DELETE FROM COMPONENT_DFN_DEPS;
DELETE FROM COMPONENT_DFN;
DELETE FROM COMPONENT;
DELETE FROM PORTAL_CONTENT_TYPE;
DELETE FROM PORTAL_CATEGORY;
DELETE FROM PORTAL_BASE;
DELETE FROM PORTAL_EDITION;
DELETE FROM PORTAL_DFN;
DELETE FROM PORTAL;
DELETE FROM PORTAL_EDITION;
DELETE FROM CONNECTOR_EDITION;
DELETE FROM CONNECTOR_DEPS;
DELETE FROM CONNECTOR_DFN;
DELETE FROM CONNECTOR;
DELETE FROM CONFIGURATION;
DELETE FROM CATEGORY_MAPPING;
DELETE FROM CATEGORY_EDITION;
DELETE FROM CATEGORY_L7D;
DELETE FROM CATEGORY_DFN;
DELETE FROM CATEGORY;
DELETE FROM CONTENT_TYPE_MAPPING;
DELETE FROM CONTENT_TYPE_EDITION;
DELETE FROM CONTENT_TYPE_L7D;
DELETE FROM CONTENT_TYPE_DFN;
DELETE FROM CONTENT_TYPE;
DELETE FROM SOURCE_MAPPING;
DELETE FROM ROUTING_DOMAIN;
DELETE FROM EDITION;
DELETE FROM DEVICE;
DELETE FROM ENVIRONMENT;
DELETE FROM PMS_USER;

