--
-- This file is part of Port@l
-- Port@l 3.0 - Portal Engine and Management System
-- Copyright (C) 2010  Isotrol, SA.  http://www.isotrol.com
--
-- Port@l is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- Port@l is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with Port@l.  If not, see <http://www.gnu.org/licenses/>.
--

--
-- Schema evolution for MySQL
--

--
-- Version 2.9.159 to 2.9.160
--

ALTER TABLE PORTAL_DEVICE DROP PRIMARY KEY;
ALTER TABLE PORTAL_DEVICE DROP FOREIGN KEY FK57C60189491AE9C;
ALTER TABLE PORTAL_DEVICE DROP KEY FK57C60189491AE9C;
ALTER TABLE PORTAL_DEVICE CHANGE MAPKEY_ID PRDV_DVCE_ID VARCHAR(36) NOT NULL;
ALTER TABLE PORTAL_DEVICE ADD INDEX FK57C601891B4CA0E0 (PRDV_DVCE_ID), ADD CONSTRAINT FK57C601891B4CA0E0 FOREIGN KEY (PRDV_DVCE_ID) REFERENCES DEVICE (ID);
ALTER TABLE PORTAL_DEVICE ADD PRIMARY KEY (PRTL_ID, PRDV_DVCE_ID);

ALTER TABLE PORTAL_COMPONENT_OVERRIDE DROP PRIMARY KEY;
ALTER TABLE PORTAL_COMPONENT_OVERRIDE DROP FOREIGN KEY FKD426F3A1D2101AB;
ALTER TABLE PORTAL_COMPONENT_OVERRIDE DROP KEY FKD426F3A1D2101AB;
ALTER TABLE PORTAL_COMPONENT_OVERRIDE CHANGE MAPKEY_ID PRTL_CMPT_ID VARCHAR(36) NOT NULL; 
ALTER TABLE PORTAL_COMPONENT_OVERRIDE ADD INDEX FKD426F3A15A42DA1B (PRTL_CMPT_ID), ADD CONSTRAINT FKD426F3A15A42DA1B FOREIGN KEY (PRTL_CMPT_ID) REFERENCES COMPONENT (ID);
ALTER TABLE PORTAL_COMPONENT_OVERRIDE ADD PRIMARY KEY (PRTL_ID, PRTL_CMPT_ID);

--
-- Version 2.9.181 to 2.9.182
--

ALTER TABLE CATEGORY ADD EVER_PUBLISHED BIT;
ALTER TABLE CATEGORY_DFN ADD EVER_PUBLISHED BIT;
ALTER TABLE CONNECTOR ADD EVER_PUBLISHED BIT;
ALTER TABLE CONNECTOR_DFN ADD EVER_PUBLISHED BIT;
ALTER TABLE CONTENT_TYPE ADD EVER_PUBLISHED BIT;
ALTER TABLE CONTENT_TYPE_DFN ADD EVER_PUBLISHED BIT;
ALTER TABLE PORTAL ADD EVER_PUBLISHED BIT;
ALTER TABLE PORTAL_DFN ADD EVER_PUBLISHED BIT;
